name: Crystal CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: shards install
      
    - name: Run Code Format
      run: crystal tool format --check
      
    - name: Run Ameba Checks
      run: bin/ameba
      
    - name: Run tests
      run: crystal spec
